### ISSUE TITLE
vue-js-cron/light crashes for Vue 2

### ISSUE THREAD

**Issue by smetanamolokovich** [abichinger/vue-js-cron#16]
After installing the vue-js-cron/light@1.0.4 and initializing it, app crashes. 

Error:
`Module not found: Error: Can't resolve '@vue-js-cron/core/src/fields/multiple' in 'C:\Users\user\Desktop\vue-js-cron-test\node_modules\@vue-js-cron\light\dist'`

**Comment by abichinger** [comment]
Thank you for reporting this issue.
solved by: d4f432d34fddf26164c9d8b155ce25d03e202af4
[vue-js-cron/light@1.0.5](https://www.npmjs.com/package/@vue-js-cron/light/v/1.0.5) should work.
