### ISSUE TITLE
Export VueCronEditor component in Light for Local Registration 

### ISSUE THREAD

**Issue by toshsan** [abichinger/vue-js-cron#18]
The control is amazing. 👏
Issue: Currently the control to be registered at app global scope (according to the doc). I could not see any exports at index.js that allows local registration. 

We should be able to do something like the following:
import { VueCronEditor } from "@vue-js-cron/light"

1. It's a best practice to export both, so users will have a choice.
2. Happy to make a pull request.

Thanks for the great component.

Note: I was able to destruct the default export like this. But  a named export will be great.
import cronLight from "@vue-js-cron/light";
import "@vue-js-cron/light/dist/light.css";

const { component: CronLight } = cronLight;

**Comment by abichinger** [comment]
75f7f18be30f1cd98388869606884659a3346f43 adds named exports.
Thank you for the suggestion!
