### ISSUE TITLE
element-plus版本无法正常使用的问题

### ISSUE THREAD

**Issue by Shimmers688** [abichinger/vue-js-cron#21]
当我在Vue3项目中按需引入Element Plus时，然后按照起步文档安装并引入vue-js-cron/element-plus，运行其中的example后，页面上仅展示为一行文本，不能点击，也没有el-button的样式。请问如何解决这个问题？

**Comment by abichinger** [comment]
Hello @Shimmers688 

Sorry, but I'm not quite sure what you have done.
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

Google Translate:
> 你好@Shimmers688
>
>对不起，但我不太确定你做了什么。
>你能提供一个最小的可重现的例子吗？

**Comment by Shimmers688** [comment]
截图如下：
![image](https://user-images.githubusercontent.com/88917934/230850254-6a52b5bf-2eea-47be-9774-be967e28a86d.png)

**Comment by Shimmers688** [comment]
demo如下：
[demo@vue-js-cron_element-plus.zip](https://github.com/abichinger/vue-js-cron/files/11188595/demo%40vue-js-cron_element-plus.zip)
请注意 readme.md 文件中的内容

**Comment by Shimmers688** [comment]
在 main.ts 文件中全局引入 Element-Plus 后可以正常使用
```typescript
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

import cronElementPlus from '@vue-js-cron/element-plus'
import '@vue-js-cron/element-plus/dist/element-plus.css'

createApp(App).use(router).use(ElementPlus).use(cronElementPlus).mount('#app')
```
