### ISSUE TITLE
I want to use Chinese, but the interface is abnormal

### ISSUE THREAD

**Issue by helloann** [abichinger/vue-js-cron#24]
![2CBD6FED2494B14701A17F4E26DA727F](https://user-images.githubusercontent.com/19811278/234542632-feb836de-1495-4f3d-8550-40793859780a.jpg)

import "@vue-js-cron/light"
and then locale="cn"
but some is chinese, other not.

Looking forward to your reply

**Comment by helloann** [comment]
<cronLight v-model="value" locale="cn” @error="error=$event"></cronLight>

**Comment by abichinger** [comment]
Hello @helloann,

have you tried `zh-cn`?

**Comment by helloann** [comment]
It doesn't work either.

**Comment by helloann** [comment]
#23 I checked it. It seems the locale zh-cn didn't push on @vue-js-cron/light 1.0.5 for vue2.

**Comment by abichinger** [comment]
I'm sorry, but I'm probably not going to maintain the vue2 version any longer.

**Comment by helloann** [comment]
After dig study your code. I use locale="zh-cn" ad custom-locale to solve it. It's successful. 
Thanks again.
