### ISSUE TITLE
Period picker does not display selected value

### ISSUE THREAD

**Issue by lami4** [abichinger/vue-js-cron#27]
Hi, I am using CronLight in my project and encountered an issue after installing it. The period picker does not display the selected value (span contains no value).
Year is selected as a period:
![image](https://github.com/abichinger/vue-js-cron/assets/7568754/0d48f943-26f7-4c06-8cfb-90a278513b88)
![image](https://github.com/abichinger/vue-js-cron/assets/7568754/2ffa9358-2bab-40d3-bfdb-3b82b537b633)

Hour is selected as a period:
![image](https://github.com/abichinger/vue-js-cron/assets/7568754/870eb725-f7a1-4346-ad28-63858cde54f2)
![image](https://github.com/abichinger/vue-js-cron/assets/7568754/dd92cc99-95cc-4874-ae46-6e2adeae8c7d)
Options are displayed just fine though:
![image](https://github.com/abichinger/vue-js-cron/assets/7568754/016c23cb-1653-40c3-8dc5-234f039d6798)
Vue version: 2.6.11, CronLight version: 1.0.5.
Component code:
```
<template>
    <div class="getting-started-light">
        <CronLight v-model="value" @error="error=$event"/>
        <div>cron expression: {{value}}</div>
    </div>
</template>

<script>
export default {
    name: "CronExpressionEditor",
    props: {
        init: {
            type: String,
            default: '* * * * *'
        }
    },
    data() {
        return {
            value: this.init,
            error: ''
        }
    }
}
</script>
<style>
</style>
```

**Comment by abichinger** [comment]
![image](https://github.com/abichinger/vue-js-cron/assets/8122139/45e34f4f-6481-47c8-8734-28db9d6cb71c)

![image](https://github.com/abichinger/vue-js-cron/assets/8122139/5ed1fbe6-170a-4a1c-ae95-65080126d0e0)
Computed values look fine.

Looks like the fallback content for the [default slot](https://github.com/abichinger/vue-js-cron/blob/21d11c1b5d8bcc2fe235b93db898a5ac63dda659/light/src/components/CustomSelect.vue#LL4C35-L4C35) of the `custom-select` component is not rendered.

**Comment by lami4** [comment]
@abichinger Another guess is you use a self closing tag [here](https://github.com/abichinger/vue-js-cron/blob/21d11c1b5d8bcc2fe235b93db898a5ac63dda659/light/src/CronEditor.vue#L8). Maybe using opening and closing tag with no content inside will fix the issue.

**Comment by Yunchitz** [comment]
Hello Guys! Is there any progress? Have same issue on latest vue3 version

**Comment by abichinger** [comment]
@Yunchitz Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.). Otherwise I can't help.
Please open a new issue if you need further assistance, because I think your issue is not related to this one.

**Comment by Yunchitz** [comment]
Yap, we just remove migration flag COMPONENT_V_MODEL, and it works fine now. Thx a lot
