### ISSUE TITLE
安装element-plus版本报错

### ISSUE THREAD

**Issue by Marilynlee** [abichinger/vue-js-cron#30]
<img width="880" alt="image" src="https://github.com/abichinger/vue-js-cron/assets/17672560/0669be02-633d-439c-a814-148aa53d9863">

**Comment by abichinger** [comment]
Hi,

[@vue-js-cron/core@3.7.1](https://www.npmjs.com/package/@vue-js-cron/core/v/3.7.1) was published 4 months ago. It is strange that npm can't resolve the dependency.

On my local machine it works just fine.
```bash
$ npm install @vue-js-cron/element-plus@latest --loglevel verbose
npm verb cli /home/andreas/.nvm/versions/node/v18.17.0/bin/node /home/andreas/.nvm/versions/node/v18.17.0/bin/npm
npm info using npm@9.6.7
npm info using node@v18.17.0
npm verb title npm install @vue-js-cron/element-plus@latest
npm verb argv "install" "@vue-js-cron/element-plus@latest" "--loglevel" "verbose"
npm http fetch GET 200 https://registry.npmjs.org/@vue-js-cron%2felement-plus 1882ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/@element-plus%2ficons-vue 225ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/element-plus 329ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@vue-js-cron%2fcore 1209ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/vue 419ms (cache updated)
...
```

Try running the command with `--loglevel verbose` to get a detailed error message

**Comment by Marilynlee** [comment]
this is the error log
----------------------------
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/**/**/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/**/**/.npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm info @vue-js-cron/element-plus@last
23 verbose argv "info" "@vue-js-cron/element-plus@last" "--loglevel" "verbose"
24 timing npm:load:setTitle Completed in 14ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/**/**/.npm/_logs
28 verbose logfile /**/**/.npm/_logs/2023-08-03T08_53_21_967Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 37ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 http fetch GET 200 https://registry.npmmirror.com/@vue-js-cron%2felement-plus 328ms (cache revalidated)
36 timing command:info Completed in 334ms
37 verbose stack Error: No match found for version last
37 verbose stack     at View.getData (/usr/local/lib/node_modules/npm/lib/commands/view.js:241:18)
37 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
37 verbose stack     at async View.exec (/usr/local/lib/node_modules/npm/lib/commands/view.js:111:28)
37 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
38 verbose statusCode 404
39 verbose pkgid @vue-js-cron/element-plus@last
40 verbose cwd /**/**/
41 verbose Darwin 22.5.0
42 verbose node v16.20.0
43 verbose npm  v8.19.4
44 error code E404
45 error 404 No match found for version last
46 error 404
47 error 404  '@vue-js-cron/element-plus@last' is not in this registry.
48 error 404
48 error 404 Note that you can also install from a
49 error 404 tarball, folder, http url, or git url.
50 verbose exit 1
51 timing npm Completed in 384ms
52 verbose code 1
53 error A complete log of this run can be found in:
53 error     /**/**/.npm/_logs/2023-08-03T08_53_21_967Z-debug-0.log

**Comment by abichinger** [comment]
Hi,

please run
```
npm install @vue-js-cron/element-plus@latest --loglevel verbose
```
According to your log you tried to install `@vue-js-cron/element-plus@last`. The right package should be `@vue-js-cron/element-plus@latest`

**Comment by Marilynlee** [comment]
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/.../.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/.../.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
14 timing config:load:global Completed in 3ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install @vue-js-cron/element-plus@latest
23 verbose argv "install" "@vue-js-cron/element-plus@latest" "--loglevel" "verbose"
24 timing npm:load:setTitle Completed in 18ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 6ms
27 verbose logfile logs-max:10 dir:/.../.npm/_logs
28 verbose logfile /.../.npm/_logs/2023-08-04T01_56_34_580Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 45ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 537ms
37 timing arborist:ctor Completed in 0ms
38 http fetch GET 200 https://registry.npmmirror.com/@vue-js-cron%2felement-plus 815ms (cache revalidated)
39 timing idealTree:userRequests Completed in 826ms
40 silly idealTree buildDeps
41 silly fetch manifest @vue-js-cron/element-plus@1.2.3
42 silly placeDep ROOT @vue-js-cron/element-plus@1.2.3 OK for: safe-brain-tenant-fe@1.0.0 want: 1.2.3
43 silly fetch manifest @vue-js-cron/core@3.7.1
44 http fetch GET 200 https://registry.npmmirror.com/@vue-js-cron%2fcore 130ms (cache revalidated)
45 timing idealTree:#root Completed in 139ms
46 silly placeDep node_modules/@vue-js-cron/element-plus @vue-js-cron/core@ OK for: @vue-js-cron/element-plus@1.2.3 want: 3.7.1
47 timing idealTree:node_modules/@vue-js-cron/element-plus Completed in 1ms
48 timing idealTree:node_modules/@vue-js-cron/element-plus/node_modules/@vue-js-cron/core Completed in 0ms
49 timing idealTree:buildDeps Completed in 142ms
50 timing idealTree:fixDepFlags Completed in 6ms
51 timing idealTree Completed in 1513ms
52 timing command:install Completed in 1522ms
53 verbose type version
54 verbose stack @vue-js-cron/core: No matching version found for @vue-js-cron/core@3.7.1.
54 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
54 verbose stack     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
54 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
54 verbose stack     at async Promise.all (index 0)
54 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1046:5)
54 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
54 verbose stack     at async Promise.all (index 1)
54 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
54 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:145:5)
54 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
55 verbose cwd /Users/liyulong/Desktop/work/safe-brain-tenant-fe
56 verbose Darwin 22.5.0
57 verbose node v16.20.0
58 verbose npm  v8.19.4
59 error code ETARGET
60 error notarget No matching version found for @vue-js-cron/core@3.7.1.
61 error notarget In most cases you or one of your dependencies are requesting
61 error notarget a package version that doesn't exist.
62 verbose exit 1
63 timing npm Completed in 1763ms
64 verbose unfinished npm timer reify 1691114194817
65 verbose unfinished npm timer reify:loadTrees 1691114194824
66 verbose code 1
67 error A complete log of this run can be found in:
67 error     /.npm/_logs/2023-08-04T01_56_34_580Z-debug-0.log

**Comment by Marilynlee** [comment]
> Hi,
> 
> please run
> 
> ```
> npm install @vue-js-cron/element-plus@latest --loglevel verbose
> ```
> 
> According to your log you typed `@last` instead of `@latest`

it is the same error!

**Comment by abichinger** [comment]
I found the problem.

npmmirror (`https://registry.npmmirror.com/`) does not host the latest version of `@vue-js-cron/core`.
```sh
$ npm show @vue-js-cron/core@latest version --registry=https://registry.npmmirror.com/
3.7.0
$ npm show @vue-js-cron/core@latest version --registry=https://registry.npmjs.org/
3.7.1
```

The bad news is that most of the mirrors I found don't have version `3.7.1`:
- https://registry.yarnpkg.com - `3.7.1`
- http://r.cnpmjs.org - `3.7.0`
- https://registry.npm.taobao.org - `3.7.0`
- http://registry.npmjs.eu - `FETCH_ERROR`
