### ISSUE TITLE
Old Vue 2 Version - Support for {#}/{#} Every format.

### ISSUE THREAD

**Issue by barino86** [abichinger/vue-js-cron#44]
We are using the Vue2 version of this library in one of our projects and have a need to support the Every N Minute _begging at_ syntax.

Example: Every 15 minutes starting at the 5 minute mark (5/15)

Would you be open to a PR to support this additional syntax?

**Comment by abichinger** [comment]
🎉 This issue has been resolved in version @vue-js-cron/vuetify@2.2.0, @vue-js-cron/light@1.1.0 and @vue-js-cron/core@2.2.0 🎉
