### ISSUE TITLE
Get selected period for storage and than use in initialPeriod prop

### ISSUE THREAD

**Issue by yatkolenko** [abichinger/vue-js-cron#47]
Hello, is there any way to retrieve the selected period?

For example, I selected the period `day`, selected the values, then saved. When I reload the page, it opens with the maximum period, not as it was when I saved, it was a `day`.

I see an `initialPeriod` property in the documentation, so if it were possible to get the selected `period`, I could save it next to the cron value and then put that saved value into the `initialPeriod` property when I reopen the page.

Thanks!

**Comment by abichinger** [comment]
Hello!

Unfortunately this is not possible at the moment. I'm going to add an event named `update:period`, which is fired every time the period is changed.

**Comment by yatkolenko** [comment]
Thank you!!
