### ISSUE TITLE
Wrong expression on every 6 days in a month

### ISSUE THREAD

**Issue by krziin** [abichinger/vue-js-cron#49]
I have an issue when I choose every 6 days in a month

**Actual:**
- My options:
  - Every month
  - Days: _**6,12,18,24,30**_ 
  - Hour: _**0**_
  - Minute: _**0**_
- Generated cron expression: `0 0 */6 * *`
- Generated dates that cron job will be run at:
  - 2024-03-19 00:00:00 UTC
  - 2024-03-25 00:00:00 UTC
  - 2024-03-31 00:00:00 UTC
  - 2024-04-01 00:00:00 UTC
  - 2024-04-07 00:00:00 UTC
  - 2024-04-13 00:00:00 UTC
  - ...

**Expected:**
- Generated cron expression: `0 0 6,12,18,24,30 * *`
- Generated dates that cron job will be run at:
  - 2024-03-18 00:00:00 UTC
  - 2024-03-24 00:00:00 UTC
  - 2024-03-30 00:00:00 UTC
  - 2024-04-06 00:00:00 UTC
  - 2024-04-12 00:00:00 UTC
  - 2024-04-18 00:00:00 UTC
  - ...

Please check this issue. Thank you so much

**Comment by abichinger** [comment]
Thank you for bringing this to my attention. I misunderstood the */x syntax.
