### ISSUE TITLE
i  meet a error when i  npm run dev -w=light

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [abichinger/vue-js-cron#50]
![image](https://github.com/abichinger/vue-js-cron/assets/59086082/de7b417e-00af-4201-a01e-c5fe5950ba59)
![image](https://github.com/abichinger/vue-js-cron/assets/59086082/0a0c7048-5569-4484-8bfd-7894ca553d17)

i  use win11,  i don't sure whether  window and mac is different

**Comment by abichinger** [comment]
Hello @duoluodexiaoxiaoyuan 

> i use win11, i don't sure whether window and mac is different

This shouldn't cause any problems. I'm using Manjaro Linux.

Did you run `npm install` in the root directory?
Which version of `node`/`npm` are you using?

I have the following versions installed:
```bash
> node --version
v20.11.0
> npm --version
10.2.4
```

**Comment by duoluodexiaoxiaoyuan** [comment]
![image](https://github.com/abichinger/vue-js-cron/assets/59086082/ac6e3719-316d-4372-bee0-3ae0d2bce312)

this is my version,

i  run npm run dev -w=core  is ok


![image](https://github.com/abichinger/vue-js-cron/assets/59086082/9ef967d8-82a2-4759-891c-ea9aaeb3a424)

but run  npm run dev -w=light is error ,  i don't konw how to solve this problem.


![image](https://github.com/abichinger/vue-js-cron/assets/59086082/a805a52f-e6f8-4882-8955-8614b7a7e704)

**Comment by abichinger** [comment]
Try to update Node.js. Vite required Node.js >= 18.

> [Compatibility Note](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
Vite requires [Node.js](https://nodejs.org/en/) version 18+. 20+. However, some templates require a higher Node.js version to work, please upgrade if your package manager warns about it.

**Comment by duoluodexiaoxiaoyuan** [comment]
> Try to update Node.js. Vite requires Node.js >= 18.
> 
> > [Compatibility Note](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
> > Vite requires [Node.js](https://nodejs.org/en/) version 18+. 20+. However, some templates require a higher Node.js version to work, please upgrade if your package manager warns about it.

thank you reply,  I want use language is en, now it's  not  effective

![image](https://github.com/abichinger/vue-js-cron/assets/59086082/7882ece4-2d63-4a76-a9e1-8b3ebfd1ab24)
![image](https://github.com/abichinger/vue-js-cron/assets/59086082/cf92172e-85b5-4a9f-8ec3-737ba4053d12)

**Comment by abichinger** [comment]
There is a typo. It should be `locale` instead of `locate`

**Comment by duoluodexiaoxiaoyuan** [comment]
> There is a typo. It should be `locale` instead of `locate`

![image](https://github.com/abichinger/vue-js-cron/assets/59086082/6e9f5333-978a-4c29-8cd9-bafb9787867a)

i'm sad, i delete local repo, then try to install and run, still error.

i use antd-design-vue, i set locale is not effictive

**Comment by abichinger** [comment]
I just tried to run `npm run dev -w=ant` on my windows virtual machine and was met with the same error message.
```cmd
  X [ERROR] Failed to resolve entry for package "@vue-js-cron/core". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
```

To resolve this, you need to build the `core` package. I'm sorry I didn't think of this sooner.
```bash
npm run build -w=core # build core package
npm run build # Or build all packages
```

> i set locale is not effictive

Here is an example of the `cron-ant` compoent using the German locale: https://codesandbox.io/p/sandbox/vue-js-cron-ant-locale-50-x5x2pn

Changing the `locale` value after the initialization is not possible at the moment. If that's what you need, then I'll see if I can make it happen. :)

**Comment by duoluodexiaoxiaoyuan** [comment]
> I just tried to run `npm run dev -w=ant` on my windows virtual machine and was met with the same error message.
> 
> ```batchfile
>   X [ERROR] Failed to resolve entry for package "@vue-js-cron/core". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
> ```
> 
> To resolve this, you need to build the `core` package. I'm sorry I didn't think of this sooner.
> 
> ```shell
> npm run build -w=core # build core package
> npm run build # Or build all packages
> ```
> 
> > i set locale is not effictive
> 
> Here is an example of the `cron-ant` compoent using the German locale: https://codesandbox.io/p/sandbox/vue-js-cron-ant-locale-50-x5x2pn
> 
> Changing the `locale` value after the initialization is not possible at the moment. If that's what you need, then I'll see if I can make it happen. :)

very thank you continue reply my questions,  now vue-js-corn  is can run,  about locale question is resolve,  I set locale="zh-cn" is ok.

**Comment by abichinger** [comment]
I'm glad I could help. Feel free to reopen the issue if you have further questions.
