### ISSUE TITLE
Highlighting selected values in the drop-down list

### ISSUE THREAD

**Issue by yatkolenko** [abichinger/vue-js-cron#51]
Hello, i'm using element-plus type of your plugin, and found small bug, when you manually select any value in dropdown it's highlighting, but, when i just open page and i have already pre defined value, this value not highlighted in dropdown menu.

Thanks!

![image](https://github.com/abichinger/vue-js-cron/assets/21259098/efd5b34a-7470-466a-9b39-6f8f68ada31b)

**Comment by abichinger** [comment]
Hello!
Thanks for bringing this to my attention. Please let me know if the latest version fixes this bug.

**Comment by yatkolenko** [comment]
> Hello! Thanks for bringing this to my attention. Please let me know if the latest version fixes this bug.

Hello, thank you for fast update!
