### ISSUE TITLE
display error when the format is quartz and the local is cn

### ISSUE THREAD

**Issue by AcTeemo** [abichinger/vue-js-cron#52]
![image](https://github.com/abichinger/vue-js-cron/assets/35121257/144534b7-d861-4cd5-afe8-497f196e083e)

**Comment by abichinger** [comment]
Hello!

Unfortunately I don't speak Chinese, so I have to rely on someone else or on a translation service to translate it.
What is the display error you are seeing? Do you mean the seconds?

You can use the prop [`customLocale`](https://abichinger.github.io/vue-js-cron/typedoc/interfaces/_vue_js_cron_core.CronCoreProps.html#customLocale) to fix it.
