### ISSUE TITLE
selectedStr of the field goes off when selecting ranges but click  not in correct order

### ISSUE THREAD

**Issue by vniko** [abichinger/vue-js-cron#6]
Whereas it produces the correct cron string the "selectedStr" property shows the ranges incorrectly in case use did not click values one by one in correct order
![image](https://user-images.githubusercontent.com/11040360/183905047-f5b44d22-96d4-4cc3-816c-fcab828c6f6a.png)

**Comment by vniko** [comment]
My guess is that sorting should be applied to "value" before making the string value out of it 
![image](https://user-images.githubusercontent.com/11040360/183905805-903e1493-bd32-43ba-bbfb-76c88445a23a.png)

**Comment by abichinger** [comment]
@vniko Thanks!
This issue should be resolved.
If it is not, feel free to reopen the issue.
