### ISSUE TITLE
When using custom periods, the selected period is not correct

### ISSUE THREAD

**Issue by Finrod927** [abichinger/vue-js-cron#64]
Hi, and thanks for your work, the component is great!

I found a little issue when using custom periods, it appears that the "every" value is always set to the last period defined in the `periods` props:

![image](https://github.com/user-attachments/assets/a86ff457-97a6-4f99-bde7-e5e07e93702d)

As you can see, the first value (`Every month/week/day`) is always the last one declared in the `periods` props, and therefore not the correct one: in that case, it should select the `week` period to display this value.

Sorry, I did not manage to create a proper reproduction case using JSFiddle or other online tools, but the code is quite simple:
```vue
<template>
  <div class="mb-3 d-flex">
    <span class="w-200">v-model:</span>
    <pre>{{ JSON.stringify(periodicity) }}</pre>
  </div>

  <div class="mb-3">
    <span class="w-200">No periods:</span>
  
    <CronVuetify v-model="periodicity" />
  </div>

  <div class="mb-3">
    <span class="w-200">Month last in periods:</span>
  
    <CronVuetify
      v-model="periodicity"
      :periods="[
        { id: 'day', value: ['hour', 'minute'] },
        { id: 'week', value: ['dayOfWeek', 'hour', 'minute'] },
        { id: 'month', value: ['day', 'hour', 'minute'] }
      ]"
    />
  </div>
  
  <div class="mb-3">
    <span class="w-200">Week last in periods:</span>
  
    <CronVuetify
      v-model="periodicity"
      :periods="[
        { id: 'month', value: ['day', 'hour', 'minute'] },
        { id: 'day', value: ['hour', 'minute'] },
        { id: 'week', value: ['dayOfWeek', 'hour', 'minute'] }
      ]"
    />
  </div>
  
  <div class="mb-3">
    <span class="w-200">Day last in periods:</span>
  
    <CronVuetify
      v-model="periodicity"
      :periods="[
        { id: 'week', value: ['dayOfWeek', 'hour', 'minute'] },
        { id: 'month', value: ['day', 'hour', 'minute'] },
        { id: 'day', value: ['hour', 'minute'] }
      ]"
    />
  </div>
</template>

<script setup lang="ts">
import { CronVuetify } from '@vue-js-cron/vuetify'
import { ref } from 'vue'

const periodicity = ref('0 2 * * 0')
</script>

<style scoped>
.w-200 {
  display: inline-block;
  width: 200px;
}
</style>
```

**Comment by abichinger** [comment]
Hi,

> Hi, and thanks for your work, the component is great!

Thanks! I'm glad you like it.

> always the last one declared in the periods props

I have defined the default periods in the following order:

```typescript
[
  { id: 'minute', value: [] },
  { id: 'hour', value: ['minute'] },
  // ...
  { id: 'year', value: ['month', 'day', 'dayOfWeek', 'hour', 'minute'] },
]
```

I wanted the period `year` to be the default one. That is why it always picks the last declared period. I have to admit that it is probably not the best solution.
Nonetheless, you can use [CronCoreProps.period](https://abichinger.github.io/vue-js-cron/typedoc/interfaces/_vue_js_cron_core.CronCoreProps.html#period) to override the default behaviour.

I didn't quite understand which period you think would be the correct one. Why should the `week` period be picked? 
```

**Comment by Finrod927** [comment]
Ahah, a bit lazy here I see 😉
We all are the same 😅

In the case of `0 2 * * 0`, it means "every sunday at 2:00", which means only the phrasing of the week period is correct:
- with month period: "Every month on every day at 2:00" is not correct
- with day period: "Every day at 2:00" is not correct
- but with week period: "Every week on sunday at 2:00" is correct

I'm on vacations for few days, but I will try to play with `period` props to see if I can get what I want :)

Have a great day, and thanks for the quick answer!

**Comment by abichinger** [comment]
> Ahah, a bit lazy here I see 😉

I plead guilty 😅

Thank you for the detailed explanation, now I understand the issue you have.
Usually, if a user selects a period [all hidden fields will be set to `*`](https://github.com/abichinger/vue-js-cron/blob/2fcb845452d2666831d2c231fc2eca5b479dc3b8/core/src/components/cron-core.ts#L183), but this does not happen when you initialize the component with an improper period. I can't think of a good solution right now, but I'll think about it.

Let me know when you find a solution.

Have a great vacation!

**Comment by abichinger** [comment]
Please let me know if 9321c709e2991dcb3d27b42ae3dc4a48569f5715 resolves your issue. The commit is included in the latest release.

**Comment by Finrod927** [comment]
Hi and thanks for the work!

In my initial case of this issue, it seems to be fixed:
![image](https://github.com/user-attachments/assets/8851ce61-9797-4eb2-8b61-30843576a146)

But as it did not work in my complete application, I made more tests and found that it is working fine when the `ref` is initialized with a value, but not when setting a new value dynamically.

I made a Gist with the code: https://gist.github.com/Finrod927/424060fa1d671228b32cd25e249edd49

For instance, when clicking on the "0 1 * 3 4" button, the value is set to "0 1 * * 4" and not "0 1 * 3 4":
![image](https://github.com/user-attachments/assets/15c23631-2aad-4f62-850f-0cdadbebab6e)

**Comment by abichinger** [comment]
Hi,

I think using the same `ref` for multiple instances could cause problems. In your example the value of the "No periods" instance would be set to `"0 1 * 3 4"`, but the other instances set it to `"0 1 * * 4"`.

I made CodeSandbox with separated values: https://codesandbox.io/p/sandbox/elegant-minsky-84555d

When the `week` period is selected and you set the value to `"0 1 * 3 4"`, then the month field with value `3` is hidden. I think hidden fields should not have a value, therefore the component sets the month field to `*`. This is currently the expected behaviour. What would you expect?

**Comment by Finrod927** [comment]
Oh! Indeed, you're right!
Well, I think I will need to use the full mode in that case.

Thanks for your work and quick responses!
