### ISSUE TITLE
please support arco design

### ISSUE THREAD

**Issue by catch6** [abichinger/vue-js-cron#66]
please support arco design

https://arco.design/vue/docs/start

**Comment by abichinger** [comment]
Hi,

Thank you for the suggestion, I'm always open to support new UI frameworks.
Are you interested in implementing it yourself? I could write a short guide on how to add a framework to `vue-js-cron`.

**Comment by catch6** [comment]
@abichinger yes, i like do it

**Comment by abichinger** [comment]
Here is the guide: https://github.com/abichinger/vue-js-cron/blob/main/CONTRIBUTING.md#add-a-new-ui-framework
Please let me know if anything is unclear.
