### ISSUE TITLE
Problem with danish locale in values

### ISSUE THREAD

**Issue by Lars-Sommer** [abichinger/vue-js-cron#67]
Hi. 

Thanks for this project, looking forward to work with it :)

However, I have a problem setting it up properly. I would prefer the Vuetify setup, but when I am running it the editor is not shown and I get a 'Failed to resolve component: v-col...' console error. (I am using vuetify v ^3.4.2). 

So I am using the core setup, which seems to work. I need it to be on danish though, so I set locale="da" on the component. This works with labels but not values:

![image](https://github.com/user-attachments/assets/9c7b1638-2371-496a-b171-d1de025e0102)

I´ve tried specifying the translation as custom-locale but that doesent help either.

I can see that the same issue is on the demo page (https://abichinger.github.io/vue-js-cron/demo.html) when you select danish:

![image](https://github.com/user-attachments/assets/4c6a25c0-86cb-4688-b484-f5f04078b158)

How to deal with this?

This is my code:

```
<template>
	<cron-core
		v-model="cronExpression"
		v-slot="{ fields, period, error }"
		@error="error = $event"
		locale="da"
		:periods="[
			{ id: 'day', value: ['hour', 'minute'] },
			{ id: 'week', value: ['dayOfWeek', 'hour', 'minute'] },
			{ id: 'month', value: ['day', 'hour', 'minute'] },
		]"
	>
		<div>
			<!-- period selection -->
			{{ period.prefix }}
			<v-chip>
				{{ period.attrs.modelValue }}
				<v-menu activator="parent">
					<v-list>
						<v-list-item v-for="item in period.items" :key="item.id" @click="period.events['update:model-value'](item.id)"> {{ item.text }} </v-list-item>
					</v-list>
				</v-menu>
			</v-chip>
			{{ period.suffix }}

			<!-- cron expression fields -->
			<template v-for="f in fields" :key="f.id">
				{{ f.prefix }}

				<v-chip>
					{{ f.selectedStr }}
					<v-menu activator="parent" :close-on-content-click="false">
						<!-- list of field items -->
						<v-list :selected="f.attrs.modelValue" @update:selected="f.events['update:model-value']">
							<v-list-item v-for="item in f.items" :value="item.value" :key="item.value">
								{{ item.text }}
							</v-list-item>
						</v-list>
					</v-menu>
				</v-chip>
				{{ f.suffix }}
			</template>

			<div>
				{{ cronExpression }}
			</div>
		</div>
	</cron-core>
</template>

<script lang="ts">
import { Component, Prop, Watch, Vue } from 'vue-facing-decorator';
import { CronCore } from '@vue-js-cron/core';

@Component({
	components: { CronCore },
})
export default class CronSelector extends Vue {
	cronExpression: string = '* * * * *';
	error: string = '';
}
</script>

```

Thanks alot :)

**Comment by abichinger** [comment]
Hi,

> I have a problem setting it up properly. I would prefer the Vuetify setup, but when I am running it the editor is not shown and I get a 'Failed to resolve component: v-col...' console error. (I am using vuetify v ^3.4.2).

I'm going to see if I can reproduce the error on my end.

> I need it to be on danish though, so I set locale="da" on the component. This works with labels but not values

It seems like the danish localization is incomplete. Could you help me translate it? I have made a commit to outline all missing translations: 8b73e1f38b31f7400459f18a53db1396a749e42c

**Comment by Lars-Sommer** [comment]
Furthermore, I am wondering about this description difference. I am no cron expert at all, but shouldnt the day description be the same in both vanilla and quartz cron?
![image](https://github.com/user-attachments/assets/8a0c875e-de85-4b4f-83da-6c675608130f)

![image](https://github.com/user-attachments/assets/a0ab5186-37c5-4776-b5e1-742af4628368)

**Comment by abichinger** [comment]
> In english it is called 'Every day', 'Every month', 'Every year' etc. But in the problematic danish language its called 'Hver dag', 'Hver måned' and 'Hvert år' - with a 't' at the end at some of the period definitions. 'Hver' is common gender noun and and 'Hvert' is neuter gender noun. I cannot see that your library supports this difference, or maybe I am missing something?

The default prefix for the danish localization is 'Hver'. This value is defined by the property `Localization['*'].prefix`. You can override the default value by setting `Localization.year.prefix` to 'Hvert'.

> Furthermore, I am wondering about this description difference. I am no cron expert at all, but shouldnt the day description be the same in both vanilla and quartz cron?

From the Cron Trigger Tutorial:

> ? (“no specific value”) - useful when you need to specify something in one of the two fields in which the character is allowed, but not the other. For example, if I want my trigger to fire on a particular day of the month (say, the 10th), but don’t care what day of the week that happens to be, I would put “10” in the day-of-month field, and “?” in the day-of-week field. See the examples below for clarification.

> Support for specifying both a day-of-week and a day-of-month value is not complete (you must currently use the ‘?’ character in one of these fields).

You can read more about the cron quartz format at: https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

**Comment by Lars-Sommer** [comment]
> The default prefix for the danish localization is 'Hver'. This value is defined by the property Localization['*'].prefix. You can override the default value by setting Localization.year.prefix to 'Hvert'.
Got it. I´ve added the prefix where it was relevant, and have now created a created PR.

> You can read more about the cron quartz format at: https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html
Thanks for the clarification 👍

**Comment by Lars-Sommer** [comment]
Regarding the vuetify error, I found out why it did not work. 
I did not include components and directives in the createVuetify method when initlizating vuetify. This worked for me:

```
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';

... createVuetify({
	components,
	directives,
...
```
@abichinger 
By the way, when do you think a new version with the danish translations will be available?

**Comment by abichinger** [comment]
> I did not include components and directives in the createVuetify method when initlizating vuetify. This worked for me.

Great! I'm glad you figured it out.

> By the way, when do you think a new version with the danish translations will be available?

Probably today.
