### ISSUE TITLE
support Monday as 1

### ISSUE THREAD

**Issue by catch6** [abichinger/vue-js-cron#68]
How to use 1-7 to represent Monday to Sunday, starting with 1 to represent Monday
I use springtask
<img width="589" alt="image" src="https://github.com/user-attachments/assets/db472a3a-3b39-485a-ae0c-a0400e93ea77">

**Comment by abichinger** [comment]
I have added a new format called `spring` with sunday as 0

**Comment by catch6** [comment]
missed a second
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/e1b7cd4a-8944-4288-85c8-f01204814bc7">

**Comment by abichinger** [comment]
The spring format does include seconds. 
https://codesandbox.io/p/sandbox/vue-js-cron-light-65-forked-zxtgsv?workspaceId=57ec16e4-4cf0-436c-82f3-18f93e1fbc40

Please make sure you use the latest version.
