### ISSUE TITLE
How can I translate the days of the week

### ISSUE THREAD

**Issue by ortizvinicius** [abichinger/vue-js-cron#9]
I was able to translate the other texts through the custom locale object but could not find how to translate the days of the week (Sunday, Monday...) 

Could you help me?

![image](https://user-images.githubusercontent.com/1380574/203416355-1376f032-34a8-4a02-951c-d61caf92508a.png)

**Comment by abichinger** [comment]
Hello @ortizvinicius,

setting `locale="pt"` should work.

Could you share your custom locale object so I can add it to the library? 
Or create a PR for it, if you want.

**Comment by ortizvinicius** [comment]
Thanks, it works now.

I´ve created the PR to add portuguese translation.

**Comment by abichinger** [comment]
Nice! I'm going to review it soon.
